# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven, Docker BUild & Push (order)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  DOCKER_IMAGE_NAME: order
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v5
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Set Execute Permission for Maven Wrapper
      run: chmod +x mvnw
      
    - name: login to docker
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    #- name: Package JAR Artifact
    #  run: ./mvnw clean package
    #- name: Build with Maven
    #  run: ./mvnw spring-boot:build-image 
    
        
    #- name: Publish Docker Image
    #  run: docker push ${{ env.DOCKER_IMAGE_NAME }}
    - name: Build
      run: ./mvnw spring-boot:build-image -Dspring-boot.build-image.imageName=urbandave/order:${{ github.run_number }}
    - name: Push
      run: docker push urbandave/order:${{ github.run_number }}
   # - name: Build, Tag and Push to Docker Hub
    #  run: |
        # 1. Den vollst√§ndigen Namen konstruieren (Syntax ist notwendig!)
     #   FULL_TAG="${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.run_number }}"
        
      #  echo "Building image $FULL_TAG..."
        
        # 2. Image bauen
       # ./mvnw spring-boot:build-image \
        #  -Dspring-boot.build-image.imageName=${FULL_TAG} 
        
        # 3. Taggen und Pushen
        #docker push ${FULL_TAG}
